[project]
name = "smart-voice-robot"
version = "0.1.0"
description = "基于行为树的人形机器人"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-anthropic>=1.3.2",
    "loguru>=0.7.0",
    "langchain-core",
    "langchain-ollama",
    "langchain-openai>=1.1.8",
    "numpy",
    "ollama>=0.6.1",
    "opencv-python>=4.13.0.90",
    "pyagxarm",
    "py-trees>=2.4.0",
    "pyyaml>=6.0.3",
    "pyyaml>=6.0.3",
    "sherpa-onnx",
    "sounddevice>=0.5.5",
    "websocket-client>=1.8.0",
    "fastapi>=0.135.3",
    "uvicorn>=0.44.0",
    "websockets>=16.0",
    "dexhand-sdk-python",
    "prompt-toolkit",
]

[project.optional-dependencies]
openai = ["langchain-openai"]
anthropic = ["langchain-anthropic"]
online = ["langchain-openai", "langchain-anthropic"]

[[tool.uv.index]]
url = "https://uv.agentsmirror.com/pypi/simple"
default = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
sherpa-onnx = { path = "../sherpa-onnx" }
pyagxarm = {path = "../pyAgxArm" }
dexhand_sdk_python = {path = "../dexhand_sdk_python"}

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
