[project]
name = "pytree-learing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-core",
    "langchain-ollama",
    "langchain-openai>=1.1.8",
    "numpy",
    "ollama>=0.6.1",
    "opencv-python>=4.13.0.90",
    "py-trees>=2.4.0",
    "pyserial>=3.5",
    "sherpa-onnx",
    "sounddevice>=0.5.5",
]

[project.optional-dependencies]
openai = ["langchain-openai"]
anthropic = ["langchain-anthropic"]
online = ["langchain-openai", "langchain-anthropic"]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
sherpa-onnx = { path = "../sherpa-onnx" }
