"""监控面板可编辑配置：字段白名单与表单分区（与 config.yaml 对应）。"""
from __future__ import annotations

# 与 config._SECRET_FIELDS 对齐：API Key 等仅环境变量，不进 Web
MONITOR_EDITABLE_FIELDS: frozenset[str] = frozenset({
    # 模型路径
    "asr_model_dir", "kws_model_dir", "tts_model_dir", "vad_model_path",
    # 唤醒 / KWS
    "wake_mode", "kws_keywords_file", "kws_keywords_score",
    "kws_keywords_threshold", "kws_num_trailing_blanks",
    # ASR
    "asr_backend", "cloud_asr_strategy", "cloud_asr_fallback_to_local",
    "iflytek_iat_language", "iflytek_iat_domain", "iflytek_iat_accent",
    "iflytek_iat_eos_ms", "cloud_asr_preroll_seconds",
    # TTS
    "tts_speaker_id", "tts_speed", "tts_volume", "tts_max_chars_per_chunk",
    "tts_sentence_pause", "tts_clause_pause", "tts_backend",
    "cloud_tts_fallback_to_local",
    "mimo_tts_model", "mimo_tts_voice", "mimo_tts_style", "mimo_tts_audio_format",
    "mimo_tts_base_url", "mimo_tts_timeout",
    "iflytek_tts_vcn", "iflytek_tts_speed",
    # VAD / 音频设备
    "vad_threshold", "vad_min_silence_duration", "vad_min_speech_duration",
    "input_device_hint", "output_device_hint",
    # 对话
    "dialog_timeout", "continuous_dialog", "interrupt_min_speech_seconds",
    # 相机
    "camera_backend", "default_camera", "camera_http_base_url", "camera_http_timeout",
    "camera_ros_node_name", "camera_ros_qos_depth", "camera_ros_warmup_seconds",
    "camera_save_dir", "camera_record_seconds", "cameras",
    # 夹爪
    "gripper_enabled", "gripper_adapter_type", "gripper_default_speed",
    "gripper_speed_close", "gripper_speed_open", "gripper_open_value", "gripper_close_value",
    "gripper_shake_cycles", "gripper_post_reset_sleep", "gripper_safe_current",
    "left_gripper", "right_gripper",
    # LLM / VLM / 规划
    "llm_provider", "llm_model", "llm_base_url", "llm_max_history",
    "llm_request_timeout", "llm_system_prompt",
    "vlm_provider", "vlm_model", "vlm_base_url", "vlm_system_prompt",
    "use_llm_planner", "planner_system_prompt",
    # 意图 / 模板（JSON）
    "intent_patterns", "tts_responses", "interrupt_wakeup_responses",
  # 机械臂
    "robot_arm_enabled", "robot_arm_robot", "robot_arm_comm", "robot_arm_firmware",
    "robot_arm_channels", "robot_arm_teach_save_dir",
    "robot_arm_replay_speed_percent", "robot_arm_enable_timeout",
    "describe_left_palm_preset_group", "describe_left_palm_preset_arm_side",
    "describe_right_palm_preset_group", "describe_right_palm_preset_arm_side",
    "describe_left_palm_preset_capture_delay_s", "describe_right_palm_preset_capture_delay_s",
    "robot_arm_keyword_actions",
    # 启动 / 系统 / 日志 / 监控
    "startup_sound_enabled", "startup_sound_text",
    "tick_interval", "num_threads", "onnx_provider", "verbose",
    "log_dir", "log_retention", "log_level",
    "enable_monitor", "monitor_port",
    "monitor_restart_on_save", "monitor_systemd_unit", "monitor_systemctl_use_sudo",
})

# type: select | text | number | boolean | textarea | json
MONITOR_CONFIG_SECTIONS: list[dict] = [
    {
        "id": "basic",
        "title": "基础模式",
        "icon": "⬡",
        "fields": [
            {"key": "wake_mode", "label": "唤醒模式", "type": "select",
             "options": ["software"], "hint": "当前仅支持 software"},
            {"key": "asr_backend", "label": "ASR 后端", "type": "select",
             "options": ["local", "iflytek_cloud"]},
            {"key": "cloud_asr_strategy", "label": "云 ASR 策略", "type": "select",
             "options": ["streaming", "endpoint_once"]},
            {"key": "cloud_asr_fallback_to_local", "label": "ASR 云失败回退本地", "type": "boolean"},
            {"key": "tts_backend", "label": "TTS 后端", "type": "select",
             "options": ["local", "iflytek_cloud", "mimo_cloud"]},
            {"key": "cloud_tts_fallback_to_local", "label": "TTS 云失败回退本地", "type": "boolean"},
            {"key": "use_llm_planner", "label": "LLM 多步规划器", "type": "boolean"},
            {"key": "continuous_dialog", "label": "连续对话", "type": "boolean",
             "hint": "true=回复后继续聆听"},
        ],
    },
    {
        "id": "kws",
        "title": "唤醒词",
        "icon": "◉",
        "fields": [
            {"key": "kws_keywords_file", "label": "关键词文件", "type": "text"},
            {"key": "kws_keywords_threshold", "label": "检测阈值", "type": "number",
             "min": 0.01, "max": 1, "step": 0.01},
            {"key": "kws_keywords_score", "label": "关键词加分", "type": "number", "step": 0.1},
        ],
    },
    {
        "id": "llm",
        "title": "LLM / VLM",
        "icon": "◈",
        "fields": [
            {"key": "llm_provider", "label": "LLM 提供商", "type": "select",
             "options": ["ollama", "openai", "deepseek", "anthropic"]},
            {"key": "llm_model", "label": "LLM 模型", "type": "text"},
            {"key": "llm_base_url", "label": "LLM Base URL", "type": "text"},
            {"key": "llm_request_timeout", "label": "LLM 超时 (秒)", "type": "number", "min": 1, "max": 120, "step": 0.5},
            {"key": "llm_max_history", "label": "对话历史轮数", "type": "number", "min": 2, "max": 30, "step": 1},
            {"key": "llm_system_prompt", "label": "LLM 系统提示词", "type": "textarea", "rows": 4},
            {"key": "vlm_provider", "label": "VLM 提供商", "type": "select",
             "options": ["ollama", "openai", "deepseek", "anthropic"]},
            {"key": "vlm_model", "label": "VLM 模型", "type": "text"},
            {"key": "vlm_base_url", "label": "VLM Base URL", "type": "text"},
            {"key": "vlm_system_prompt", "label": "VLM 系统提示词", "type": "textarea", "rows": 3},
            {"key": "planner_system_prompt", "label": "规划器提示词", "type": "textarea", "rows": 3},
        ],
    },
    {
        "id": "audio",
        "title": "音频 & 对话",
        "icon": "◎",
        "fields": [
            {"key": "tts_speed", "label": "TTS 语速", "type": "number", "min": 0.5, "max": 2, "step": 0.1},
            {"key": "tts_volume", "label": "TTS 音量增益", "type": "number", "min": 0.1, "max": 3, "step": 0.1},
            {"key": "tts_speaker_id", "label": "本地 TTS 说话人 ID", "type": "number", "min": 0, "max": 99, "step": 1},
            {"key": "iflytek_tts_vcn", "label": "讯飞发音人", "type": "text"},
            {"key": "mimo_tts_model", "label": "MiMo TTS 模型", "type": "text"},
            {"key": "mimo_tts_voice", "label": "MiMo 音色", "type": "text"},
            {"key": "mimo_tts_style", "label": "MiMo 风格", "type": "textarea", "rows": 2},
            {"key": "dialog_timeout", "label": "对话超时 (秒)", "type": "number", "min": 5, "max": 120, "step": 1},
            {"key": "interrupt_min_speech_seconds", "label": "打断最短语音 (秒)", "type": "number",
             "min": 0.1, "max": 3, "step": 0.1},
            {"key": "vad_threshold", "label": "VAD 阈值", "type": "number", "min": 0.1, "max": 0.9, "step": 0.05},
            {"key": "input_device_hint", "label": "麦克风设备名子串", "type": "text"},
            {"key": "output_device_hint", "label": "扬声器设备名子串", "type": "text"},
        ],
    },
    {
        "id": "camera",
        "title": "相机",
        "icon": "▣",
        "fields": [
            {"key": "camera_backend", "label": "相机后端", "type": "select",
             "options": ["local", "http", "ros"]},
            {"key": "default_camera", "label": "默认相机", "type": "select",
             "options": ["head", "left_palm", "right_palm"]},
            {"key": "camera_http_base_url", "label": "HTTP 相机基址", "type": "text"},
            {"key": "camera_http_timeout", "label": "HTTP 超时 (秒)", "type": "number", "min": 1, "max": 30, "step": 0.5},
            {"key": "camera_save_dir", "label": "保存目录", "type": "text"},
            {"key": "camera_record_seconds", "label": "录像时长 (秒)", "type": "number", "min": 1, "max": 120, "step": 1},
            {"key": "cameras", "label": "相机列表 (JSON)", "type": "json", "rows": 8,
             "hint": "head / left_palm / right_palm"},
        ],
    },
    {
        "id": "gripper",
        "title": "夹爪",
        "icon": "✊",
        "fields": [
            {"key": "gripper_enabled", "label": "启用夹爪", "type": "boolean"},
            {"key": "gripper_adapter_type", "label": "适配器", "type": "select",
             "options": ["zlg_mini", "zlg_200u", "lys_mini"]},
            {"key": "gripper_speed_close", "label": "合拢速度", "type": "number", "min": 1, "max": 2000, "step": 10},
            {"key": "gripper_speed_open", "label": "张开速度", "type": "number", "min": 1, "max": 2000, "step": 10},
            {"key": "left_gripper", "label": "左夹爪 (JSON)", "type": "json", "rows": 4},
            {"key": "right_gripper", "label": "右夹爪 (JSON)", "type": "json", "rows": 4},
        ],
    },
    {
        "id": "arm",
        "title": "机械臂",
        "icon": "🦾",
        "fields": [
            {"key": "robot_arm_enabled", "label": "启用机械臂", "type": "boolean"},
            {"key": "robot_arm_robot", "label": "机型", "type": "text"},
            {"key": "robot_arm_comm", "label": "通信", "type": "text"},
            {"key": "robot_arm_firmware", "label": "固件版本", "type": "text"},
            {"key": "robot_arm_channels", "label": "CAN 通道 (JSON)", "type": "json", "rows": 3},
            {"key": "robot_arm_replay_speed_percent", "label": "回放速度 %", "type": "number",
             "min": 1, "max": 100, "step": 1},
            {"key": "describe_left_palm_preset_group", "label": "左掌心预置动作组", "type": "text"},
            {"key": "describe_right_palm_preset_group", "label": "右掌心预置动作组", "type": "text"},
            {"key": "robot_arm_keyword_actions", "label": "关键词动作 (JSON)", "type": "json", "rows": 6},
        ],
    },
    {
        "id": "intent",
        "title": "意图 & 话术",
        "icon": "💬",
        "fields": [
            {"key": "intent_patterns", "label": "意图关键词 (JSON)", "type": "json", "rows": 8},
            {"key": "tts_responses", "label": "TTS 固定回复 (JSON)", "type": "json", "rows": 6},
            {"key": "interrupt_wakeup_responses", "label": "打断唤醒回复 (JSON)", "type": "json", "rows": 3},
            {"key": "startup_sound_enabled", "label": "启动提示音", "type": "boolean"},
            {"key": "startup_sound_text", "label": "启动提示语文本", "type": "text"},
        ],
    },
    {
        "id": "system",
        "title": "系统",
        "icon": "⚙",
        "fields": [
            {"key": "tick_interval", "label": "Tick 间隔 (秒)", "type": "number", "min": 0.01, "max": 1, "step": 0.01},
            {"key": "num_threads", "label": "推理线程数", "type": "number", "min": 1, "max": 16, "step": 1},
            {"key": "onnx_provider", "label": "ONNX 设备", "type": "select", "options": ["cpu", "cuda"]},
            {"key": "log_level", "label": "日志级别", "type": "select",
             "options": ["DEBUG", "INFO", "WARNING", "ERROR"]},
            {"key": "log_dir", "label": "日志目录", "type": "text"},
            {"key": "log_retention", "label": "日志保留", "type": "text"},
            {"key": "verbose", "label": "详细日志", "type": "boolean"},
            {"key": "enable_monitor", "label": "启用监控面板", "type": "boolean"},
            {"key": "monitor_port", "label": "监控端口", "type": "number", "min": 1024, "max": 65535, "step": 1},
            {"key": "monitor_restart_on_save", "label": "保存后重启服务", "type": "boolean",
             "hint": "写入 config.yaml 后 systemctl restart"},
            {"key": "monitor_systemd_unit", "label": "systemd 单元名", "type": "text",
             "hint": "如 smart-voice-robot.service"},
            {"key": "monitor_systemctl_use_sudo", "label": "restart 使用 sudo -n", "type": "boolean"},
            {"key": "asr_model_dir", "label": "ASR 模型目录", "type": "text"},
            {"key": "kws_model_dir", "label": "KWS 模型目录", "type": "text"},
            {"key": "tts_model_dir", "label": "TTS 模型目录", "type": "text"},
            {"key": "vad_model_path", "label": "VAD 模型路径", "type": "text"},
        ],
    },
]
